Simplify CI workflow by reducing OS matrix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,7 +8,7 @@ jobs:
     strategy:
       fail-fast: false  # https://github.com/actions/runner-images#available-images
       matrix:  # https://github.com/actions/python-versions/releases
-        os: [ubuntu-26.04, ubuntu-26.04-arm, macos-latest, macos-26-intel]  # , windows-latest, windows-11-arm]
+        os: [ubuntu-26.04]  # , ubuntu-26.04-arm, macos-latest, macos-26-intel, windows-latest, windows-11-arm]
         # python-version: ["3.10", "3.12", "3.14", "3.14t", "3.15", "pypy-3.11"]
         python-version: [3.x]
     runs-on: ${{ matrix.os }}
@@ -33,10 +33,12 @@ jobs:
           python-version: ${{ matrix.python-version }}
           allow-prereleases: true
       - run: pip install --upgrade pip
-      - run: pip install --editable . || true  # TODO: Local install always fails!
-      - run: luarocks install lunatic-python || true  # TODO: Always fails! luarocks: command not found
-      - run: pip install lunatic-python || true  # Install from PyPI -- Always fails!
-      - run: pip install lunatic-python-universal  # Install from PyPI
+      - env:
+          PYTHON_LIBRT: "x64"
+        run: pip install --editable .
+      # - run: luarocks install lunatic-python || true  # TODO: Always fails! luarocks: command not found
+      # - run: pip install lunatic-python || true  # Install from PyPI -- Always fails!
+      # - run: pip install lunatic-python-universal  # Install from PyPI
       - shell: python  # Sanity check
         run: |
           import lua
